### ISSUE TITLE
Is this needed if using modern JetBrains.Annotations from NuGet?

### ISSUE THREAD

**Issue by drewnoakes** [Fody/JetBrainsAnnotations#5]
Is this Fody addin needed if you use the `JetBrains.Annotations` NuGet package. The attributes themselves are conditionally defined and so are excluded from builds by default, meaning you don't have to deploy `JetBrains.Annotations.dll`, but can still benefit from these annotations at design time.

Just wondering if I'm missing something. Thanks!

**Comment by SimonCropp** [comment]
@drewnoakes i think u r correct and this project is now redundant. paging @controlflow can u confirm? if so i will deprecate it and forward people to JetBrains.Annotations proper

**Comment by SimonCropp** [comment]
i am going with "No"

**Comment by dennisroche** [comment]
@drewnoakes I was wondering the same thing. I believe that this project is indeed obsolete as all the annotation classes are defined with `[Conditional("JETBRAINS_ANNOTATIONS")]` and will be stripped out as part of the build. 

Source: https://www.jetbrains.com/help/resharper/2016.2/Code_Analysis__Annotations_in_Source_Code.html

**Comment by ndrwrbgs** [comment]
I know this is closed, but stumbled upon this comment. I think a difference is (maybe new since the comment date) that this project also makes the `ExternalAnnotations` file. Purpose for the necromancy - does anyone on this thread knows of another way to make the `ExternalAnnotations` file from the `[NotNull]`s in the code?

**Comment by drewnoakes** [comment]
https://youtrack.jetbrains.com/issue/RSRP-453476
